site_name: Matt Parker's Maths Puzzles

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - assets/javascripts/math.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
